// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7PF8PtMTw1Ad_pKgHlARVji4-Bipw0Y',
    appId: '1:241946134230:web:d6b658327a76d1cb10ab77',
    messagingSenderId: '241946134230',
    projectId: 'ubermenshc-f7ead',
    authDomain: 'ubermenshc-f7ead.firebaseapp.com',
    storageBucket: 'ubermenshc-f7ead.appspot.com',
    measurementId: 'G-X5NECCL20G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsty5WHNn1DTys3QeamG4RIQ2CCttBb4U',
    appId: '1:241946134230:android:f76370090bbdfed810ab77',
    messagingSenderId: '241946134230',
    projectId: 'ubermenshc-f7ead',
    storageBucket: 'ubermenshc-f7ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXmmhvq_rdAG-l6eIHN3H8MygYArWhwA',
    appId: '1:241946134230:ios:ba12580923d11d6810ab77',
    messagingSenderId: '241946134230',
    projectId: 'ubermenshc-f7ead',
    storageBucket: 'ubermenshc-f7ead.appspot.com',
    iosClientId: '241946134230-4fmdmckji8ges1elvmh33m68dvr97hd5.apps.googleusercontent.com',
    iosBundleId: 'com.northwolf.ubermenshc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpXmmhvq_rdAG-l6eIHN3H8MygYArWhwA',
    appId: '1:241946134230:ios:ba12580923d11d6810ab77',
    messagingSenderId: '241946134230',
    projectId: 'ubermenshc-f7ead',
    storageBucket: 'ubermenshc-f7ead.appspot.com',
    iosClientId: '241946134230-4fmdmckji8ges1elvmh33m68dvr97hd5.apps.googleusercontent.com',
    iosBundleId: 'com.northwolf.ubermenshc',
  );
}
